# Generated by Django 5.1.12 on 2025-09-26 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('device_id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('note', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'devices',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DevicesView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=256)),
                ('device_properties_name', models.CharField(max_length=256)),
                ('device_properties_note', models.CharField(max_length=256)),
                ('device_properties_value', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'view_devices',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sensors',
            fields=[
                ('id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'sensors',
                'managed': False,
            },
        ),
    ]
